package guru.nicks.commons.cucumber.sortableid;

import guru.nicks.commons.cucumber.world.TextWorld;
import guru.nicks.commons.sortableid.TimeSortableId;
import guru.nicks.commons.sortableid.TimeSortableIdSettings;

import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import lombok.RequiredArgsConstructor;
import org.apache.commons.lang3.StringUtils;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@RequiredArgsConstructor
public class CustomEpochSteps {

    // DI
    private final TextWorld textWorld;

    @When("sequence number is converted to time-sortable")
    public void idIsConvertedToTimeSortable() {
        // max. timestamp and sequence
        //textWorld.setDate(Instant.parse("2568-08-24T00:00:00Z"));
        //textWorld.setInput("922337203685477579");

        textWorld.setOutput(new TimeSortableId(textWorld.getDate(),
                // numbers may contain whitespaces, for readability
                Long.parseLong(StringUtils.deleteWhitespace(textWorld.getInput()))
        ).getId());
    }

    @When("time-sortable ID is decoded")
    public void timeSortableIdIsParsed() {
        Optional<TimeSortableId> timeSortableId = TimeSortableId.decode(textWorld.getInput());

        textWorld.setOutput(
                timeSortableId.map(TimeSortableId::getSequence)
                        .map(Object::toString)
                        .orElse(null));

        textWorld.setParsedDate(
                timeSortableId.map(TimeSortableId::getTimestamp).orElse(null));
    }

    /**
     * Decodes the ID generated by {@link #idIsConvertedToTimeSortable()} (stored as the single output value) and
     * publishes the decoded sequence and timestamp the same way {@link #timeSortableIdIsParsed()} does.
     */
    @When("generated ID is decoded back")
    public void generatedIdIsDecodedBack() {
        String generatedId = textWorld.getOutput().get(0);
        Optional<TimeSortableId> decoded = TimeSortableId.decode(generatedId);

        textWorld.setOutput(
                decoded.map(TimeSortableId::getSequence)
                        .map(Object::toString)
                        .orElse(null));

        textWorld.setParsedDate(
                decoded.map(TimeSortableId::getTimestamp).orElse(null));
    }

    /**
     * Checks the round-trip precision: the timestamp decoded from a generated ID may differ from the original one
     * because of approximate subsecond encoding, but never by more than the configured maximum delta.
     */
    @Then("decoded timestamp is within the maximum encoded timestamp delta")
    public void decodedTimestampIsWithinMaximumEncodedTimestampDelta() {
        assertThat(textWorld.getParsedDate())
                .as("parsedDate")
                .isNotNull();

        long deltaMs = Math.abs(textWorld.getDate().toEpochMilli() - textWorld.getParsedDate().toEpochMilli());
        assertThat(deltaMs)
                .as("decoded timestamp delta, ms")
                .isLessThanOrEqualTo(TimeSortableIdSettings.DEFAULT.getMaxEncodedTimestampDeltaMs());
    }

    /**
     * Ensures the stateless default timestamp encoder is shared and not allocated per call.
     */
    @Then("default timestamp encoder is reused between calls")
    public void defaultTimestampEncoderIsReusedBetweenCalls() {
        assertThat(TimeSortableIdSettings.DEFAULT.getTimestampEncoder())
                .isSameAs(TimeSortableIdSettings.DEFAULT.getTimestampEncoder());
    }

    /**
     * Ensures the stateless default ID composer is shared and not allocated per call.
     */
    @Then("default ID composer is reused between calls")
    public void defaultIdComposerIsReusedBetweenCalls() {
        assertThat(TimeSortableIdSettings.DEFAULT.getIdComposer())
                .isSameAs(TimeSortableIdSettings.DEFAULT.getIdComposer());
    }

    /**
     * Ensures the stateless default ID checksummer is shared and not allocated per call.
     */
    @Then("default ID checksummer is reused between calls")
    public void defaultIdChecksummerIsReusedBetweenCalls() {
        assertThat(TimeSortableIdSettings.DEFAULT.getIdChecksummer())
                .isSameAs(TimeSortableIdSettings.DEFAULT.getIdChecksummer());
    }

}
